# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ImprovedICP
                                 A QGIS plugin
 Grid map fusion Qgis plugin using improved ICP algorithm
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-06-06
        copyright            : (C) 2018 by Tang-XY
        email                : 2015302590078@whu.edu.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ImprovedICP class from file ImprovedICP.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .improved_ICP import ImprovedICP
    return ImprovedICP(iface)
